### PR TITLE
Replay packing fix

### PR DESCRIPTION
**Pull request by tiinanen**
Hi, I noticed that I couldn't unpack some of my AI replays, which are generated using Smibu's Elma physics implementation.

While I started digging, I noticed some problems with the replay (un)packing code and some misinterpretations of the replay format and its events.

I tried to fix the biggest issues with this PR. It could be improved further for sure.

### CODE REVIEW

**Comment by sigvef** [comment]
Nice! The changes all look good. Can you bundle an example replay in the testsuite that didn't work before, but now does?

**Comment by tiinanen** [comment]
Ok, I added an example rec and a test for it.

**Comment by jonsykkel** [comment]
### **_praying this will get merged in 2019_**

**Comment by sigvef** [comment]
Sorry for the delay. Thanks for the reminder! :)

**Pull request merged**
