### PR TITLE
Fix error.py bug ignoring qexit and qkiller

### PR DESCRIPTION
**Pull request by sunlelma**
Just reviewed all the code & noticed that my error checking function only treated qfood as objects, but ignored qexit and qkiller.

This code fixes this bug.

Sorry for new pull request

### CODE REVIEW

**Comment by sigvef** [comment]
I took the liberty of rebasing your commit on master and making a new pull request here: https://github.com/sigvef/elma/pull/13 . If it is ok with you I will merge that, if not you can resolve the conflicts here instead :)

**Comment by sigvef** [comment]
> Sorry for new pull request

The more the merrier 💃

**Comment by sunlelma** [comment]
#13 looks good! We can use that instead :)

**Comment by sigvef** [comment]
Merged via #13.

**Pull request closed without merging**
